### ISSUE TITLE
Add font to brew

### ISSUE THREAD

**Issue by chrede88** [kvndrsslr/sketchybar-app-font#138]
It would be great if this font could be added to brew. This makes it easier to keep the font up-to-date, as most mac users use brew to manage their fonts.

**Comment by chrede88** [comment]
I've created a PR. This was my first PR to brew, so it might not be smooth ride. Let's see.
Link: https://github.com/Homebrew/homebrew-cask/pull/193463

**Comment by kvndrsslr** [comment]
Thank you for your contributio @chrede88. It might be beneficial to install the various mapping scripts as well, as updates to the font alone won't automatically lead to more icons being available in sketchybar.

**Comment by chrede88** [comment]
I'm not sure that's a good idea, here's why:

1) The font can be used standalone, also for other things. For this reason, adding a bunch of files that might not be used by the users is not nice.

2) Automatically overriding config files is not necessarily the best default.

3) I'm pretty sure the brew guys won't let us add "random" config files along side the font.

What we can do is to add a message at the end of the brew install/update reminding people to update the Sketchybar mapping script if needed.

**Comment by chrede88** [comment]
> Such a description in caveats would be useful! I've just installed this and I'm unsure of what I should be doing/downloading separately from the brew package.

I'll see if I can add something meaningful to the cask.
