### ISSUE TITLE
Cypress icon

### ISSUE THREAD

**Issue by Arelav** [kvndrsslr/sketchybar-app-font#15]
Thanks for SketchyBar, your config and this font.
If possible can Cypress icon be added?
https://github.com/cypress-io/cypress/blob/develop/packages/frontend-shared/src/assets/icons/cypress-logo_x16.svg

**Comment by kvndrsslr** [comment]
I am not the SketchyBar author, nor do I process icon requests. See the repos README.

**Comment by Arelav** [comment]
My apologies

**Comment by Arelav** [comment]
I hope is everything was done right
https://github.com/kvndrsslr/sketchybar-app-font/pull/16
