### ISSUE TITLE
Request to Add Icons for Fusion 360 and Bambulab Slicer

### ISSUE THREAD

**Issue by 10bn** [kvndrsslr/sketchybar-app-font#19]
Hello, I'm using Sketchybar and I would like to request icons for Fusion 360 and Bambulab Slicer. 

I have prepared SVG icons here: 
![bambulab_slicer](https://github.com/kvndrsslr/sketchybar-app-font/assets/46263124/80100eee-fb1a-4f82-b6fd-bf776c0338c8)
![fusion_360](https://github.com/kvndrsslr/sketchybar-app-font/assets/46263124/2301a0e0-7df2-4295-9ccb-0e19e6489898)

**Comment by kvndrsslr** [comment]
Those icons will need to be in a stamp-like single color format as the others.
Follow the guide in the README and prepare a PR and I'll gladly merge it.

**Comment by kvndrsslr** [comment]
Oh didn't mean to close it
