### ISSUE TITLE
Request to add PyCharm icon

### ISSUE THREAD

**Issue by corruptmane** [kvndrsslr/sketchybar-app-font#28]
Some of JetBrains IDEs icons are already present, like IntelliJ Idea or WebStorm, but PyCharm.

**Comment by corruptmane** [comment]
![optimized_pycharm](https://github.com/kvndrsslr/sketchybar-app-font/assets/40265576/8461c410-8cc6-42c0-82bd-c62794adc9ba)

is that ok?

**Comment by corruptmane** [comment]
Is that icon ok?

![optimized_pycharm](https://github.com/kvndrsslr/sketchybar-app-font/assets/40265576/f53a53f4-73e8-4530-af60-2291ea563387)

**Comment by kvndrsslr** [comment]
I believe that seems good, make a PR and I'll approve it :)
