### ISSUE TITLE
How to Obtain a ttf

### ISSUE THREAD

**Issue by iortego42** [kvndrsslr/sketchybar-app-font#3]
I have a question, how should I process all the svg files i have added and generete a new .ttf file ?

**Comment by kvndrsslr** [comment]
This is a node package, therefore:
```bash
npm i 
npm run build
```

**Comment by iortego42** [comment]
I have add some icons for my pentesting tools to render perfectly and it is working awesome. I would like to know how is this actually works, because I want to use all this icons and use it to be displayed on terminal, by mapping every icon in the kitty.conf file, but the problem is that if I use the :program name: notation, it does not work. How it is actually working and why skecthy bar identifyes the icons by tipping :name: in stead of interprete that as an string?

**Comment by kvndrsslr** [comment]
It seems like ligatures should be enabled in kitty per default
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.disable_ligatures

Although if it does not work with ligatures enabled I'm not sure where to start troubleshooting tbh.

**Comment by iortego42** [comment]
Thank's for answering! Yeah, by default kitty enable ligatures, by the way I have also enable it in my configuration file, now the problem is  that I need to make kitty to recognise the sketchy bar font, because it is not doing it.
Thank you very much!
