### ISSUE TITLE
Unlicense invalid in some jurisdictions

### ISSUE THREAD

**Issue by Cu3PO42** [kvndrsslr/sketchybar-app-font#55]
Hi, I see you have added the Unlicense to your project. Unfortunately, the Unlicense is invalid in some jurisdictions, such as Germany, where I live. Under German law it is impossible to renounce all rights to one's creative work.

This means that to German users, this is the same as having no license and also that any contributions by German users cannot be licensed under the Unlicense. This includes my contribution of the Orion logo.

Please consider using a different license, such as CC0, which has equivalent intent, but works in all jurisdictions that I'm aware of.

**Comment by kvndrsslr** [comment]
Thanks for bringing this to my attention. I lack knowledge pertaining to licensing and for all practical purposes I honestly don't think it makes a difference for a project like this but it's still good to do it right 👍🏼
