### ISSUE TITLE
Request to Add icon for Inkdrop

### ISSUE THREAD

**Issue by louishuyng** [kvndrsslr/sketchybar-app-font#66]
Inkdrop is quite popular note app https://www.inkdrop.app/

**Comment by rferrpla** [comment]
Hi @louishuyng. 
In order to add the icon, I would need the exact application name (I don´t have installed on my machine).

Could you share the output of the next command with us?
`lsappinfo info -only name "Inkdrop"`
(The application must be opened in order to get the command to work)

**Comment by louishuyng** [comment]
Hi @rferrpla here is the output of the command lsappinfo info -only name "Inkdrop"
```
"LSDisplayName"="Inkdrop"

```
